export const url = {
    auth: "https://node-db-tutorial1945.herokuapp.com/api/auth",
    msg: "http://localhost:7900/api/messages",
    user: "https://node-db-tutorial1945.herokuapp.com/api/users",
    book: "https://node-db-tutorial1945.herokuapp.com/api/books",
    lessons: "http://localhost:7900/api/lessons",
}

export const book1 = {
    product_name: "Yagate Kimi ni Naru",
    product_volume: 1,
    product_price: 8.90,
    product_author: "Nakatani Nio",
    product_category: "Yuri",
    product_add: false,
    product_rank: 4,
    product_img: "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/6269/9781626923539.jpg",
    product_desc: "Bloom into You is an ongoing series and will be released as single volumes with at least one full colour illustration per book. Yuu has always loved shoujo manga and awaits the day she gets a love confession that sends her heart aflutter with bubbles and hearts, and yet when a junior high classmate confesses his feelings to her...she feels nothing. Disappointed and confused, Yuu enters high school still unsure howto respond. That's when Yuu sees the beautiful student council president Nanami turn down a suitor with such maturity that she's inspired to ask her for help. But when the next person to confess to Yuu is Nanami herself, has her shoujo romance finally begun?",
    product_format: "Paperback",
    product_pages: 180,
    product_dimention: "127 x 180 x 10mm | 136, 08g",
    product_publish_day: "03 Jan 2017",
    product_editor: "Seven Seas Entertainment, LLC",
    product_publish_location: "West Hollywood, United States",
    product_languaje: "English",
    product_ISBN10: 1626923531,
    product_ISBN13: 978,
    product_selling_rank: 5231,
    product_similar: JSON.stringify(["Citrus", "Sadamaki Koto"]),
    //product_seller: 1,
    product_percentage: 11,
    product_total_sell: 0,
}

export const book2 = {
    product_name: "Yagate Kimi ni Naru",
    product_volume: 2,
    product_price: 9.10,
    product_author: "Nakatani Nio",
    product_add: false,
    product_rank: 4,
    product_img: "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/6269/9781626924796.jpg",
    product_desc: "Bloom into You is a charming love story about two young women who together discover that their dreams of a heart-pounding romance can indeed come true. With endearing characters and a beautiful art style, Bloom into You is a fan favourite series within the genre that will be a hit for fans of Citrus and Girl Friends. Bloom into You is an ongoing series and will be released as single volumes with at least one full-colour illustration per book. Yuu has always loved shoujo manga and fantasizes about the day that she too will get a love confession that will send her heart a- flutter. Yet when a male classmate confesses his feelings for her...she feels nothing. Disappointed and confused, Yuu enters high school still unsure how to respond. That's when Yuu sees the beautiful student council president Nanami turn down a suitor with such maturity and finesse that Yuu is inspired to ask her for advice. But when the next person to confess to Yuu is the alluring Nanami herself, has Yuu's shoujo romance finally begun?",
    product_format: "Paperback",
    product_pages: 180,
    product_dimention: "127 x 180 x 10mm | 136, 08g",
    product_publish_day: " 03 Jan 2017",
    product_editor: "Seven Seas Entertainment, LLC",
    product_publish_location: "West Hollywood, United States",
    product_languaje: "English",
    product_ISBN10: 1626924791,
    product_ISBN13: 9781,
    product_selling_rank: 23379,
    product_similar: JSON.stringify(["Citrus", "Sadamaki Koto"]),
    //product_seller: 1,
    product_percentage: 14,
    product_total_sell: 0,
    product_category: "Yuri"
}